### ISSUE TITLE
구매자 거래완료페이지에서 일자가 나오지 않습니다.

### ISSUE THREAD

**Issue by HeartOfTheBeast** [10kseok/3DPrintingPlatform#13]
12번 줄 {% if trade_log %}을 판매자 거래완료페이지처럼 {% if trade %}로 바꿨더니 일자가 나옵니다.
바꿔도 되는 건가요?

**Comment by 10kseok** [comment]
변수명을 변경하면서 저 부분만 수정을 안했었네요,,,
